# Generated by Django 3.0.6 on 2020-06-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(),
        ),
    ]
