# Generated by Django 3.0.6 on 2020-06-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200624_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
